### ISSUE TITLE
Path won't be parsed as lower case

### ISSUE THREAD

**Issue by vzaidman** [garycourt/uri-js#11]
URI.normalize("https://WWW.GOOGLE.cOM/A/B/C.htmL") === "https://www.google.com/A/B/C.htmL"
Is this on purpose? because equal fails as well for now.
URI.equal("https://www.google.com/AA", "https://www.google.com/aa") === false

**Comment by garycourt** [comment]
Yes, this is intended behaviour.

According to section 6.2.2.1 of RFC 3986, path components are considered case sensitive. This also applies to HTTP schemes as defined in section 3.2.3 of RFC 2616.
