### ISSUE TITLE
Error when HOST is a IPv6.

### ISSUE THREAD

**Issue by JonDotsoy** [garycourt/uri-js#13]
This is when `HOST` use within `.serialize()` with `::`. 

Example.

Input:

```javascript
URI.serialize({
  scheme: 'http',
  port: '80',
  host: '::'
});
```

Output:

```bash
http://%3A%3A/
```

**Comment by garycourt** [comment]
RFC 3986 Section 3.2.2 requires host IPv6 addresses to be surrounded in square brackets (`[::]`).
