### ISSUE TITLE
undefined is not an object (evaluating 'URI.SCHEMES')

### ISSUE THREAD

**Issue by mixophrygian** [garycourt/uri-js#14]
Using as a dependency of oauth-signature, Line 4 /build/schemes/http.js":

`URI.SCHEMES["http"] = URI.SCHEMES["https"] =` is throwing this error.

**Comment by yagottahavehart** [comment]
@mixophrygian If you're using react-native and seeing this error (we were), it looks related to how it's requiring things.
We're still debugging to figure it out... 
Try this out:

OLD:
`///<reference path="../uri.ts"/>
if (typeof COMPILED === "undefined" && typeof URI === "undefined" && typeof require === "function")
    var URI = require("../uri");`

NEW:

`var URI = require("../uri");
///<reference path="../uri.ts"/>
if (typeof COMPILED === "undefined" && typeof URI === "undefined" && typeof require === "function")
    `

We did this in a couple places and it started to work, looking for a lasting solution now though

**Comment by mixophrygian** [comment]
Yes, I am having this problem in react-native, version 0.27.2 and oauth-signature version 1.3.1.  Unfortunately that fix didn't resolve the issue for me.

**Comment by retro** [comment]
This also failing with ClojureScript compiler. It seems that `COMPILED` is not undefined, it's a boolean

**Comment by eleanor-byhook** [comment]
Welp, if you initialize `URI.SCHEMES` as an empty object before it the http or https attributes get set, it works.

Add `URI.SCHEMES = {};` to line four.

**Comment by garycourt** [comment]
Version 3 of URI.js has been refactored and should fix this issue.
