### ISSUE TITLE
default value for func parameter(options) is not supported by ie11

### ISSUE THREAD

**Issue by GorbachevA** [garycourt/uri-js#25]
https://github.com/garycourt/uri-js/blob/29fdbec1f569971641cb3faacb32f1d14565fb0b/dist/esnext/uri.js#L174

function parse(uriString, options = {}) default value for func parameter(options) is not supported by ie11

**Comment by garycourt** [comment]
IE11 is no longer supported by Microsoft, and will thus no longer support any newer EcmaScript features. If you need IE support, use the ES5 version of URI.js at `dist/es5/uri.all.js`.
