### ISSUE TITLE
Add support for parsing query string into object

### ISSUE THREAD

**Issue by chefhoobajoob** [garycourt/uri-js#34]
Didn't see this anywhere in the tests or documentation - ignore if there's already support for this.

Looking for something that supports a usage like:
```
const uriString = 'rando://bubba-gump?hello=there&whatever=you-say'
const uri = URI.parse(uriString)
const query = URI.parseQuery(uri)
const whatever = query.whatever
```

**Comment by garycourt** [comment]
URI.js do not parse query strings as _WWW Form Url Encoded query strings_ are part of the HTML4+ spec, and not the HTTP/URI spec. As such, I made a call that it was out of scope for this project.

There are various query string parsing libraries already available such as `qs` in Node.js, or [any of these here](https://www.npmjs.com/search?q=querystring).
