### ISSUE TITLE
Invalid scheme syntax permitted

### ISSUE THREAD

**Issue by palemieux** [garycourt/uri-js#35]
`urijs.parse("any(http://www.w3.org/ns/ttml/profile/ttml2-transformation")`

does not result in an error, even though the `scheme` component of an absolute URI is constrained to `ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )` per [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.1), and the `path-noscheme` of a relative URI cannot contain a `":"` until after the first `"/".`

**Comment by garycourt** [comment]
The reason you are not seeing an error here is because URI.js does not perform validation on a parsed URI. Instead, it will try and parse the URI as permissively as it can. URI validation is not currently supported by this library.
