### ISSUE TITLE
Uri-js doesn't work in io.js (strict mode)

### ISSUE THREAD

**Issue by teologov** [garycourt/uri-js#8]
Hi, `uri-js` doesn't work in the latest version of `io.js` (strict mode). 
It fails with this error:

`.../uri-js/build/schemes/http.js:3
    URI = require("../uri");
        ^
ReferenceError: URI is not defined
    at Object.<anonymous> (/.../uri-js/build/schemes/http.js:3:9)`

**Comment by garycourt** [comment]
Should be fixed now.

**Comment by teologov** [comment]
Awesome, thanks!
